In [1]:
import pandas as pd
import numpy as np
import folium
from folium.plugins import MarkerCluster
# Import folium MousePosition plugin
from folium.plugins import MousePosition
# Import folium DivIcon plugin
from folium.features import DivIcon

In [74]:
df = pd.read_csv('https://cf-courses-data.s3.us.cloud-object-storage.appdomain.cloud/IBM-DS0321EN-SkillsNetwork/datasets/spacex_launch_geo.csv')

In [3]:
spacex_df = df[['Launch Site', 'Lat', 'Long', 'class']]
launch_sites_df = df.groupby(['Launch Site'], as_index=False).first()
launch_sites_df = launch_sites_df[['Launch Site', 'Lat', 'Long']]
launch_sites_df

    Launch Site        Lat        Long
0   CCAFS LC-40  28.562302  -80.577356
1  CCAFS SLC-40  28.563197  -80.576820
2    KSC LC-39A  28.573255  -80.646895
3   VAFB SLC-4E  34.632834 -120.610745

In [7]:
spacex_map = folium.Map(location=[39.8283,-98.5795],zoom_start=5,tiles="Cartodb positron")

In [8]:
spacex_map

In [10]:
for launch_site, lat, long in zip(launch_sites_df["Launch Site"],launch_sites_df.Lat,launch_sites_df.Long):
    circle = folium.Circle([lat,long],radius=1000,color = "red", fill=True).add_child(folium.Popup(launch_site))

    marker=folium.map.Marker(
        [lat,long],

        icon = DivIcon(
            icon_size=(20,20),
            icon_anchor=(0,0),
            html = f'<div style="font-size: 12; color:#d35400;"><b>{launch_site}</b></div>'
        )
    )

    spacex_map.add_child(circle)
    spacex_map.add_child(marker)

In [11]:
spacex_map

In [14]:
spacex_df["marker_color"] = spacex_df["class"].map({0:"red",1:"green"})

In [13]:
spacex_df.dtypes

Launch Site        str
Lat            float64
Long           float64
class            int64
dtype: object

In [15]:
spacex_df["marker_color"]

0       red
1       red
2       red
3       red
4       red
5       red
6       red
7       red
8       red
9       red
10      red
11      red
12      red
13      red
14      red
15      red
16      red
17    green
18    green
19      red
20    green
21    green
22    green
23      red
24    green
25    green
26      red
27      red
28    green
29    green
30    green
31    green
32      red
33      red
34      red
35      red
36    green
37      red
38    green
39    green
40      red
41    green
42    green
43      red
44    green
45    green
46    green
47    green
48    green
49    green
50    green
51      red
52      red
53      red
54    green
55      red
Name: marker_color, dtype: str

In [16]:
spacex_df

     Launch Site        Lat        Long  class marker_color
0    CCAFS LC-40  28.562302  -80.577356      0          red
1    CCAFS LC-40  28.562302  -80.577356      0          red
2    CCAFS LC-40  28.562302  -80.577356      0          red
3    CCAFS LC-40  28.562302  -80.577356      0          red
4    CCAFS LC-40  28.562302  -80.577356      0          red
5    CCAFS LC-40  28.562302  -80.577356      0          red
6    CCAFS LC-40  28.562302  -80.577356      0          red
7    CCAFS LC-40  28.562302  -80.577356      0          red
8    CCAFS LC-40  28.562302  -80.577356      0          red
9    CCAFS LC-40  28.562302  -80.577356      0          red
10   CCAFS LC-40  28.562302  -80.577356      0          red
11   CCAFS LC-40  28.562302  -80.577356      0          red
12   CCAFS LC-40  28.562302  -80.577356      0          red
13   CCAFS LC-40  28.562302  -80.577356      0          red
14   CCAFS LC-40  28.562302  -80.577356      0          red
15   CCAFS LC-40  28.562302  -80.577356      0          red
16   CCAFS LC-40  28.562302  -80.577356      0          red
17   CCAFS LC-40  28.562302  -80.577356      1        green
18   CCAFS LC-40  28.562302  -80.577356      1        green
19   CCAFS LC-40  28.562302  -80.577356      0          red
20   CCAFS LC-40  28.562302  -80.577356      1        green
21   CCAFS LC-40  28.562302  -80.577356      1        green
22   CCAFS LC-40  28.562302  -80.577356      1        green
23   CCAFS LC-40  28.562302  -80.577356      0          red
24   CCAFS LC-40  28.562302  -80.577356      1        green
25   CCAFS LC-40  28.562302  -80.577356      1        green
26   VAFB SLC-4E  34.632834 -120.610745      0          red
27   VAFB SLC-4E  34.632834 -120.610745      0          red
28   VAFB SLC-4E  34.632834 -120.610745      1        green
29   VAFB SLC-4E  34.632834 -120.610745      1        green
30   VAFB SLC-4E  34.632834 -120.610745      1        green
31   VAFB SLC-4E  34.632834 -120.610745      1        green
32   VAFB SLC-4E  34.632834 -120.610745      0          red
33   VAFB SLC-4E  34.632834 -120.610745      0          red
34   VAFB SLC-4E  34.632834 -120.610745      0          red
35   VAFB SLC-4E  34.632834 -120.610745      0          red
36    KSC LC-39A  28.573255  -80.646895      1        green
37    KSC LC-39A  28.573255  -80.646895      0          red
38    KSC LC-39A  28.573255  -80.646895      1        green
39    KSC LC-39A  28.573255  -80.646895      1        green
40    KSC LC-39A  28.573255  -80.646895      0          red
41    KSC LC-39A  28.573255  -80.646895      1        green
42    KSC LC-39A  28.573255  -80.646895      1        green
43    KSC LC-39A  28.573255  -80.646895      0          red
44    KSC LC-39A  28.573255  -80.646895      1        green
45    KSC LC-39A  28.573255  -80.646895      1        green
46    KSC LC-39A  28.573255  -80.646895      1        green
47    KSC LC-39A  28.573255  -80.646895      1        green
48    KSC LC-39A  28.573255  -80.646895      1        green
49  CCAFS SLC-40  28.563197  -80.576820      1        green
50  CCAFS SLC-40  28.563197  -80.576820      1        green
51  CCAFS SLC-40  28.563197  -80.576820      0          red
52  CCAFS SLC-40  28.563197  -80.576820      0          red
53  CCAFS SLC-40  28.563197  -80.576820      0          red
54  CCAFS SLC-40  28.563197  -80.576820      1        green
55  CCAFS SLC-40  28.563197  -80.576820      0          red

In [17]:
marker_cluster = MarkerCluster()

In [18]:

for lat, long, color, outcome in zip(spacex_df["Lat"],spacex_df["Long"],spacex_df["marker_color"],spacex_df["class"]):
    marker = folium.Marker(
        [lat,long],
        icon=DivIcon(
            html=f'<div style="font-size: 12; color:{color};"><b>{outcome}</b></div>'
        )
    )
    marker_cluster.add_child(marker)

In [19]:
spacex_map.add_child(marker_cluster)

In [21]:
formatter = "function(num) {return L.Util.formatNum(num, 5);};"
mouse_position = MousePosition(
    position='topright',
    separator=' Long: ',
    empty_string='NaN',
    lng_first=False,
    num_digits=20,
    prefix='Lat:',
    lat_formatter=formatter,
    lng_formatter=formatter,
)

spacex_map.add_child(mouse_position)
spacex_map

In [22]:
from math import sin, cos, sqrt, atan2, radians

def calculate_distance(lat1, lon1, lat2, lon2):
    # approximate radius of earth in km
    R = 6373.0

    lat1 = radians(lat1)
    lon1 = radians(lon1)
    lat2 = radians(lat2)
    lon2 = radians(lon2)

    dlon = lon2 - lon1
    dlat = lat2 - lat1

    a = sin(dlat / 2)**2 + cos(lat1) * cos(lat2) * sin(dlon / 2)**2
    c = 2 * atan2(sqrt(a), sqrt(1 - a))

    distance = R * c
    return distance

In [23]:
railway_marker = folium.Marker(
    location = [28.56408,-80.5868],
    icon = DivIcon(
        icon_size = (20,20),
        icon_anchor = (0,0),
        html='<div style="font-size: 12; color:blue;"><b>Closest Railway</b></div>',
    )
)
spacex_map.add_child(railway_marker)
spacex_map

In [25]:
railway_line = folium.PolyLine(locations = [[28.562302, -80.577356],[28.56408,-80.5868]],weight=1)
spacex_map.add_child(railway_line)

In [27]:
railway_line2 = folium.PolyLine(locations = [[28.563197, -80.576820],[28.56408,-80.5868]],weight=1)
spacex_map.add_child(railway_line2)
spacex_map

In [26]:
spacex_df

     Launch Site        Lat        Long  class marker_color
0    CCAFS LC-40  28.562302  -80.577356      0          red
1    CCAFS LC-40  28.562302  -80.577356      0          red
2    CCAFS LC-40  28.562302  -80.577356      0          red
3    CCAFS LC-40  28.562302  -80.577356      0          red
4    CCAFS LC-40  28.562302  -80.577356      0          red
5    CCAFS LC-40  28.562302  -80.577356      0          red
6    CCAFS LC-40  28.562302  -80.577356      0          red
7    CCAFS LC-40  28.562302  -80.577356      0          red
8    CCAFS LC-40  28.562302  -80.577356      0          red
9    CCAFS LC-40  28.562302  -80.577356      0          red
10   CCAFS LC-40  28.562302  -80.577356      0          red
11   CCAFS LC-40  28.562302  -80.577356      0          red
12   CCAFS LC-40  28.562302  -80.577356      0          red
13   CCAFS LC-40  28.562302  -80.577356      0          red
14   CCAFS LC-40  28.562302  -80.577356      0          red
15   CCAFS LC-40  28.562302  -80.577356      0          red
16   CCAFS LC-40  28.562302  -80.577356      0          red
17   CCAFS LC-40  28.562302  -80.577356      1        green
18   CCAFS LC-40  28.562302  -80.577356      1        green
19   CCAFS LC-40  28.562302  -80.577356      0          red
20   CCAFS LC-40  28.562302  -80.577356      1        green
21   CCAFS LC-40  28.562302  -80.577356      1        green
22   CCAFS LC-40  28.562302  -80.577356      1        green
23   CCAFS LC-40  28.562302  -80.577356      0          red
24   CCAFS LC-40  28.562302  -80.577356      1        green
25   CCAFS LC-40  28.562302  -80.577356      1        green
26   VAFB SLC-4E  34.632834 -120.610745      0          red
27   VAFB SLC-4E  34.632834 -120.610745      0          red
28   VAFB SLC-4E  34.632834 -120.610745      1        green
29   VAFB SLC-4E  34.632834 -120.610745      1        green
30   VAFB SLC-4E  34.632834 -120.610745      1        green
31   VAFB SLC-4E  34.632834 -120.610745      1        green
32   VAFB SLC-4E  34.632834 -120.610745      0          red
33   VAFB SLC-4E  34.632834 -120.610745      0          red
34   VAFB SLC-4E  34.632834 -120.610745      0          red
35   VAFB SLC-4E  34.632834 -120.610745      0          red
36    KSC LC-39A  28.573255  -80.646895      1        green
37    KSC LC-39A  28.573255  -80.646895      0          red
38    KSC LC-39A  28.573255  -80.646895      1        green
39    KSC LC-39A  28.573255  -80.646895      1        green
40    KSC LC-39A  28.573255  -80.646895      0          red
41    KSC LC-39A  28.573255  -80.646895      1        green
42    KSC LC-39A  28.573255  -80.646895      1        green
43    KSC LC-39A  28.573255  -80.646895      0          red
44    KSC LC-39A  28.573255  -80.646895      1        green
45    KSC LC-39A  28.573255  -80.646895      1        green
46    KSC LC-39A  28.573255  -80.646895      1        green
47    KSC LC-39A  28.573255  -80.646895      1        green
48    KSC LC-39A  28.573255  -80.646895      1        green
49  CCAFS SLC-40  28.563197  -80.576820      1        green
50  CCAFS SLC-40  28.563197  -80.576820      1        green
51  CCAFS SLC-40  28.563197  -80.576820      0          red
52  CCAFS SLC-40  28.563197  -80.576820      0          red
53  CCAFS SLC-40  28.563197  -80.576820      0          red
54  CCAFS SLC-40  28.563197  -80.576820      1        green
55  CCAFS SLC-40  28.563197  -80.576820      0          red

In [29]:
beach_marker = folium.Marker(
    [28.56282,-80.56792],
    icon = DivIcon(
        icon_size = (20,20),
        icon_anchor = (0,0),
        html='<div style="font-size: 12; color:blue;"><b>Closest Coastline</b></div>', 
    )
)
spacex_map.add_child(beach_marker)
spacex_map

In [30]:
beachline1 = folium.PolyLine(locations=[[28.563197, -80.576820],[28.56282,-80.56792]],weight=1)

In [32]:
spacex_map.add_child(beachline1)

In [33]:
spacex_map

In [34]:
beachline2 = folium.PolyLine(locations=[[28.562302, -80.577356],[28.56282,-80.56792]],weight=1)

spacex_map.add_child(beachline2)
spacex_map

In [35]:
c_railway39 = folium.Marker(
    [28.57329,-80.65401],
    icon = DivIcon(
        icon_size=(20,20),
        icon_anchor=(0,0),
        html = '<div style="font-size: 12; color:blue;"><b>Closest Railway</b></div>'
    )
)
spacex_map.add_child(c_railway39)

In [36]:
c_highway39 = folium.Marker(
    [28.57329,-80.65545],
    icon = DivIcon(
        icon_size=(20,20),
        icon_anchor=(0,0),
        html = '<div style="font-size: 12; color:blue;"><b>Closest Highway</b></div>'
    )
)

spacex_map.add_child(c_highway39)

In [37]:
line_39a = folium.PolyLine(locations = [[28.573255,-80.646895],[28.57329,-80.65545]],weight=1)
spacex_map.add_child(line_39a)

In [38]:
closest_city = folium.Marker(
    [28.6122,-80.8076],
    popup = "Titusville, FL",
    icon=DivIcon(
        icon_size=(20,20),
        icon_anchor=(0,0),
        html= '<div style="font-size: 12; color:blue;"><b>Closest City</b></div>'
    )
)

spacex_map.add_child(closest_city)

In [40]:
spacex_df["Launch Site"].unique()

<StringArray>
['CCAFS LC-40', 'VAFB SLC-4E', 'KSC LC-39A', 'CCAFS SLC-40']
Length: 4, dtype: str

In [41]:
for x in spacex_df["Launch Site"].unique():
    print(x)

CCAFS LC-40
VAFB SLC-4E
KSC LC-39A
CCAFS SLC-40

In [43]:
list_fl = list(spacex_df["Launch Site"].unique())

In [45]:
list_fl.pop(1)

'VAFB SLC-4E'

In [46]:
list_fl

['CCAFS LC-40', 'KSC LC-39A', 'CCAFS SLC-40']

In [47]:
fl_dataframe = spacex_df[spacex_df["Launch Site"] != "VAFB SLC-4E"]

In [48]:
fl_dataframe.head()

   Launch Site        Lat       Long  class marker_color
0  CCAFS LC-40  28.562302 -80.577356      0          red
1  CCAFS LC-40  28.562302 -80.577356      0          red
2  CCAFS LC-40  28.562302 -80.577356      0          red
3  CCAFS LC-40  28.562302 -80.577356      0          red
4  CCAFS LC-40  28.562302 -80.577356      0          red

In [50]:
fl_dataframe.drop(columns = ["class","marker_color"],inplace=True)

In [55]:
fl_dataframe

     Launch Site        Lat       Long
0    CCAFS LC-40  28.562302 -80.577356
36    KSC LC-39A  28.573255 -80.646895
49  CCAFS SLC-40  28.563197 -80.576820

In [54]:
fl_dataframe.drop_duplicates(inplace=True)

In [57]:
for launch, lat, long in zip(fl_dataframe["Launch Site"],fl_dataframe.Lat,fl_dataframe.Long):
    city_line = folium.PolyLine(locations = [[lat,long],[28.6122,-80.8076]],weight=1)

    spacex_map.add_child(city_line)
spacex_map

In [58]:
california_highway = folium.Marker(
    [34.63887,-120.44012],
    icon=DivIcon(
        icon_size=(20,20),
        icon_anchor=(0,0),
        html = '<div style="font-size: 12; color:blue;"><b>Closest Highway</b></div>'
    )
)

spacex_map.add_child(california_highway)

In [59]:
lompoc = folium.Marker(
    [34.6391, -120.4579],
    popup = "Lompoc, CA",
    icon=DivIcon(
        icon_size=(20,20),
        icon_anchor=(0,0),
        html = '<div style="font-size: 12; color:blue;"><b>Closest City</b></div>'
    )
)
spacex_map.add_child(lompoc)

In [60]:
cal_coast = folium.Marker(
    [34.63729, -120.6244],
    icon=DivIcon(
        icon_size=(20,20),
        icon_anchor=(0,0),
        html = '<div style="font-size: 12; color:blue;"><b>Closest Coast</b></div>'
    )
)
spacex_map.add_child(cal_coast)

In [61]:
cal_train = folium.Marker(
    [34.63679, -120.62361],
    icon=DivIcon(
        icon_size=(20,20),
        icon_anchor=(0,0),
        html = '<div style="font-size: 12; color:blue;"><b>Closest Railway</b></div>'
    )
)
spacex_map.add_child(cal_train)

In [62]:
lines_to_draw = [
    [34.63679, -120.62361],
    [34.63729, -120.6244],
    [34.6391, -120.4579],
    [34.63887,-120.44012]
]

In [63]:
spacex_df.head()

   Launch Site        Lat       Long  class marker_color
0  CCAFS LC-40  28.562302 -80.577356      0          red
1  CCAFS LC-40  28.562302 -80.577356      0          red
2  CCAFS LC-40  28.562302 -80.577356      0          red
3  CCAFS LC-40  28.562302 -80.577356      0          red
4  CCAFS LC-40  28.562302 -80.577356      0          red

In [64]:
vafb_dataframe = spacex_df[spacex_df["Launch Site"] == "VAFB SLC-4E"]

In [69]:
vafb_dataframe.drop_duplicates(inplace=True)

In [71]:
vafb_dataframe.drop(29,inplace=True)

In [72]:
vafb_dataframe

    Launch Site        Lat        Long  class marker_color
26  VAFB SLC-4E  34.632834 -120.610745      0          red

In [73]:
for coordinates in lines_to_draw:
    cal_lines = folium.PolyLine(locations = [[34.632834,-120.610745],coordinates],weight=1)

    spacex_map.add_child(cal_lines)
spacex_map

In [77]:
type(marker_cluster)

folium.plugins.marker_cluster.MarkerCluster