In [1]:
import pandas as pd
import numpy as np
import folium

In [3]:
from folium.plugins import MarkerCluster
from folium.plugins import MousePosition
from folium.features import DivIcon

In [4]:
url = "https://cf-courses-data.s3.us.cloud-object-storage.appdomain.cloud/IBM-DS0321EN-SkillsNetwork/datasets/spacex_launch_geo.csv"

In [5]:
spacex_df = pd.read_csv(url)

In [6]:
spacex_df

,Flight Number,Date,Time (UTC),Booster Version,Launch Site,Payload,Payload Mass (kg),Orbit,Customer,Landing Outcome,class,Lat,Long
0,1,2010-06-04,18:45:00,F9 v1.0 B0003,CCAFS LC-40,Dragon Spacecraft Qualification Unit,0.00,LEO,SpaceX,Failure (parachute),0,28.562302,-80.577356
1,2,2010-12-08,15:43:00,F9 v1.0 B0004,CCAFS LC-40,"Dragon demo flight C1, two CubeSats, barrel o...",0.00,LEO (ISS),NASA (COTS) NRO,Failure (parachute),0,28.562302,-80.577356
2,3,2012-05-22,7:44:00,F9 v1.0 B0005,CCAFS LC-40,Dragon demo flight C2+,525.00,LEO (ISS),NASA (COTS),No attempt,0,28.562302,-80.577356
3,4,2012-10-08,0:35:00,F9 v1.0 B0006,CCAFS LC-40,SpaceX CRS-1,500.00,LEO (ISS),NASA (CRS),No attempt,0,28.562302,-80.577356
4,5,2013-03-01,15:10:00,F9 v1.0 B0007,CCAFS LC-40,SpaceX CRS-2,677.00,LEO (ISS),NASA (CRS),No attempt,0,28.562302,-80.577356
5,7,2013-12-03,22:41:00,F9 v1.1,CCAFS LC-40,SES-8,3170.00,GTO,SES,No attempt,0,28.562302,-80.577356
6,8,2014-01-06,22:06:00,F9 v1.1,CCAFS LC-40,Thaicom 6,3325.00,GTO,Thaicom,No attempt,0,28.562302,-80.577356
7,9,2014-04-18,19:25:00,F9 v1.1,CCAFS LC-40,SpaceX CRS-3,2296.00,LEO (ISS),NASA (CRS),Controlled (ocean),0,28.562302,-80.577356
8,10,2014-07-14,15:15:00,F9 v1.1,CCAFS LC-40,OG2 Mission 1 6 Orbcomm-OG2 satellites,1316.00,LEO,Orbcomm,Controlled (ocean),0,28.562302,-80.577356
9,11,2014-08-05,8:00:00,F9 v1.1,CCAFS LC-40,AsiaSat 8,4535.00,GTO,AsiaSat,No attempt,0,28.562302,-80.577356
10,12,2014-09-07,5:00:00,F9 v1.1 B1011,CCAFS LC-40,AsiaSat 6,4428.00,GTO,AsiaSat,No attempt,0,28.562302,-80.577356
11,13,2014-09-21,5:52:00,F9 v1.1 B1010,CCAFS LC-40,SpaceX CRS-4,2216.00,LEO (ISS),NASA (CRS),Uncontrolled (ocean),0,28.562302,-80.577356
12,14,2015-01-10,9:47:00,F9 v1.1 B1012,CCAFS LC-40,SpaceX CRS-5,2395.00,LEO (ISS),NASA (CRS),Failure (drone ship),0,28.562302,-80.577356
13,15,2015-02-11,23:03:00,F9 v1.1 B1013,CCAFS LC-40,DSCOVR,570.00,Sun–Earth L1,U.S. Air Force NASA NOAA,Controlled (ocean),0,28.562302,-80.577356
14,16,2015-03-02,3:50:00,F9 v1.1 B1014,CCAFS LC-40,ABS-3A Eutelsat 115 West B,4159.00,GTO,ABS Eutelsat,No attempt,0,28.562302,-80.577356
15,17,2015-04-14,20:10:00,F9 v1.1 B1015,CCAFS LC-40,SpaceX CRS-6,1898.00,LEO (ISS),NASA (CRS),Failure (drone ship),0,28.562302,-80.577356
16,18,2015-04-27,23:03:00,F9 v1.1 B1016,CCAFS LC-40,TürkmenÄlem 52°E / MonacoSAT,4707.00,GTO,Turkmenistan National Space Agency,No attempt,0,28.562302,-80.577356
17,19,2015-06-28,14:21:00,F9 v1.1 B1018,CCAFS LC-40,SpaceX CRS-7,1952.00,LEO (ISS),NASA (CRS),Precluded (drone ship),1,28.562302,-80.577356
18,20,2015-12-22,1:29:00,F9 FT B1019,CCAFS LC-40,OG2 Mission 2 11 Orbcomm-OG2 satellites,2034.00,LEO,Orbcomm,Success (ground pad),1,28.562302,-80.577356
19,22,2016-03-04,23:35:00,F9 FT B1020,CCAFS LC-40,SES-9,5271.00,GTO,SES,Failure (drone ship),0,28.562302,-80.577356
20,23,2016-04-08,20:43:00,F9 FT B1021.1,CCAFS LC-40,SpaceX CRS-8,3136.00,LEO (ISS),NASA (CRS),Success (drone ship),1,28.562302,-80.577356
21,24,2016-05-06,5:21:00,F9 FT B1022,CCAFS LC-40,JCSAT-14,4696.00,GTO,SKY Perfect JSAT Group,Success (drone ship),1,28.562302,-80.577356
22,25,2016-05-27,21:39:00,F9 FT B1023.1,CCAFS LC-40,Thaicom 8,3100.00,GTO,Thaicom,Success (drone ship),1,28.562302,-80.577356
23,26,2016-06-15,14:29:00,F9 FT B1024,CCAFS LC-40,ABS-2A Eutelsat 117 West B,3600.00,GTO,ABS Eutelsat,Failure (drone ship),0,28.562302,-80.577356
24,27,2016-07-18,4:45:00,F9 FT B1025.1,CCAFS LC-40,SpaceX CRS-9,2257.00,LEO (ISS),NASA (CRS),Success (ground pad),1,28.562302,-80.577356
25,28,2016-08-14,5:26:00,F9 FT B1026,CCAFS LC-40,JCSAT-16,4600.00,GTO,SKY Perfect JSAT Group,Success (drone ship),1,28.562302,-80.577356
26,6,2013-09-29,16:00:00,F9 v1.1 B1003,VAFB SLC-4E,CASSIOPE,500.00,Polar LEO,MDA,Uncontrolled (ocean),0,34.632834,-120.610745
27,21,2016-01-17,18:42:00,F9 v1.1 B1017,VAFB SLC-4E,Jason-3,553.00,LEO,NASA (LSP) NOAA CNES,Failure (drone ship),0,34.632834,-120.610745
28,29,2017-01-14,17:54:00,F9 FT B1029.1,VAFB SLC-4E,Iridium NEXT 1,9600.00,Polar LEO,Iridium Communications,Success (drone ship),1,34.632834,-120.610745
29,37,2017-06-25,20:25:00,F9 FT B1036.1,VAFB SLC-4E,Iridium NEXT 2,9600.00,LEO,Iridium Communications,Success (drone ship),1,34.632834,-120.610745
30,40,2017-08-24,18:51:00,F9 FT B1038.1,VAFB SLC-4E,Formosat-5,475.00,SSO,NSPO,Success (drone ship),1,34.632834,-120.610745
31,42,2017-10-09,12:37:00,F9 B4 B1041.1,VAFB SLC-4E,Iridium NEXT 3,9600.00,Polar LEO,Iridium Communications,Success (drone ship),1,34.632834,-120.610745
32,46,2017-12-23,1:27:00,F9 FT B1036.2,VAFB SLC-4E,Iridium NEXT 4,9600.00,Polar LEO,Iridium Communications,Controlled (ocean),0,34.632834,-120.610745
33,49,2018-02-22,14:17:00,F9 FT B1038.2,VAFB SLC-4E,Paz Tintin A & B,2150.00,SSO,Hisdesat exactEarth SpaceX,No attempt,0,34.632834,-120.610745
34,51,2018-03-30,14:14:00,F9 B4 B1041.2,VAFB SLC-4E,Iridium NEXT 5,9600.00,Polar LEO,Iridium Communications,No attempt,0,34.632834,-120.610745
35,55,2018-05-22,19:47:58,F9 B4 B1043.2,VAFB SLC-4E,"Iridium NEXT 6 GRACE-FO 1, 2",6460.00,Polar LEO,Iridium Communications GFZ • NASA,No attempt,0,34.632834,-120.610745
36,30,2017-02-19,14:39:00,F9 FT B1031.1,KSC LC-39A,SpaceX CRS-10,2490.00,LEO (ISS),NASA (CRS),Success (ground pad),1,28.573255,-80.646895
37,31,2017-03-16,6:00:00,F9 FT B1030,KSC LC-39A,EchoStar 23,5600.00,GTO,EchoStar,No attempt,0,28.573255,-80.646895
38,32,2017-03-30,22:27:00,F9 FT B1021.2,KSC LC-39A,SES-10,5300.00,GTO,SES,Success (drone ship),1,28.573255,-80.646895
39,33,2017-05-01,11:15:00,F9 FT B1032.1,KSC LC-39A,NROL-76,3696.65,LEO,NRO,Success (ground pad),1,28.573255,-80.646895
40,34,2017-05-15,23:21:00,F9 FT B1034,KSC LC-39A,Inmarsat-5 F4,6070.00,GTO,Inmarsat,No attempt,0,28.573255,-80.646895
41,35,2017-06-03,21:07:00,F9 FT B1035.1,KSC LC-39A,SpaceX CRS-11,2708.00,LEO (ISS),NASA (CRS),Success (ground pad),1,28.573255,-80.646895
42,36,2017-06-23,19:10:00,F9 FT B1029.2,KSC LC-39A,BulgariaSat-1,3669.00,GTO,Bulsatcom,Success (drone ship),1,28.573255,-80.646895
43,38,2017-07-05,23:38:00,F9 FT B1037,KSC LC-39A,Intelsat 35e,6761.00,GTO,Intelsat,No attempt,0,28.573255,-80.646895
44,39,2017-08-14,16:31:00,F9 B4 B1039.1,KSC LC-39A,SpaceX CRS-12,3310.00,LEO (ISS),NASA (CRS),Success (ground pad),1,28.573255,-80.646895
45,41,2017-09-07,14:00:00,F9 B4 B1040.1,KSC LC-39A,Boeing X-37B OTV-5,4990.00,LEO,U.S. Air Force,Success (ground pad),1,28.573255,-80.646895
46,43,2017-10-11,22:53:00,F9 FT B1031.2,KSC LC-39A,SES-11 / EchoStar 105,5200.00,GTO,SES EchoStar,Success (drone ship),1,28.573255,-80.646895
47,44,2017-10-30,19:34:00,F9 B4 B1042.1,KSC LC-39A,Koreasat 5A,3500.00,GTO,KT Corporation,Success (drone ship),1,28.573255,-80.646895
48,54,2018-05-11,20:14:00,F9 B5 B1046.1,KSC LC-39A,Bangabandhu-1,3600.00,GTO,Thales-Alenia/BTRC,Success (drone ship),1,28.573255,-80.646895
49,45,2017-12-15,15:36:00,F9 FT B1035.2,CCAFS SLC-40,SpaceX CRS-13,2205.00,LEO (ISS),NASA (CRS),Success (ground pad),1,28.563197,-80.576820
50,47,2018-01-08,1:00:00,F9 B4 B1043.1,CCAFS SLC-40,Zuma,3696.65,LEO,Northrop Grumman,Success (ground pad),1,28.563197,-80.576820
51,48,2018-01-31,21:25:00,F9 FT B1032.2,CCAFS SLC-40,GovSat-1 / SES-16,4230.00,GTO,SES,Controlled (ocean),0,28.563197,-80.576820
52,50,2018-03-06,5:33:00,F9 B4 B1044,CCAFS SLC-40,Hispasat 30W-6 PODSat,6092.00,GTO,Hispasat NovaWurks,No attempt,0,28.563197,-80.576820
53,52,2018-04-02,20:30:00,F9 B4 B1039.2,CCAFS SLC-40,SpaceX CRS-14,2647.00,LEO (ISS),NASA (CRS),No attempt,0,28.563197,-80.576820
54,53,2018-04-18,22:51:00,F9 B4 B1045.1,CCAFS SLC-40,Transiting Exoplanet Survey Satellite (TESS),362.00,HEO,NASA (LSP),Success (drone ship),1,28.563197,-80.576820
55,56,2018-06-04,4:45:00,F9 B4 B1040.2,CCAFS SLC-40,SES-12,5384.00,GTO,SES,No attempt,0,28.563197,-80.576820

In [7]:
spacex_df.info()

<class 'pandas.DataFrame'>
RangeIndex: 56 entries, 0 to 55
Data columns (total 13 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   Flight Number      56 non-null     int64
 1   Date               56 non-null     str
 2   Time (UTC)         56 non-null     str
 3   Booster Version    56 non-null     str
 4   Launch Site        56 non-null     str
 5   Payload            56 non-null     str
 6   Payload Mass (kg)  56 non-null     float64
 7   Orbit              56 non-null     str
 8   Customer           56 non-null     str
 9   Landing Outcome    56 non-null     str
 10  class              56 non-null     int64
 11  Lat                56 non-null     float64
 12  Long               56 non-null     float64
dtypes: float64(3), int64(2), str(8)
memory usage: 5.8 KB

In [14]:
launch_locations = folium.Map(location=[39.8283,-98.5795],zoom_start=4,tiles="Cartodb positron")
launch_locations

In [15]:
for latitude, longitude in zip(spacex_df["Lat"],spacex_df["Long"]):
    folium.features.CircleMarker(location=[latitude,longitude],radius=2,color="blue").add_to(launch_locations)
launch_locations

In [16]:
for latitude, longitude in zip(spacex_df["Lat"],spacex_df["Long"]):
    print(latitude, longitude)

28.56230197 -80.57735648
28.56230197 -80.57735648
28.56230197 -80.57735648
28.56230197 -80.57735648
28.56230197 -80.57735648
28.56230197 -80.57735648
28.56230197 -80.57735648
28.56230197 -80.57735648
28.56230197 -80.57735648
28.56230197 -80.57735648
28.56230197 -80.57735648
28.56230197 -80.57735648
28.56230197 -80.57735648
28.56230197 -80.57735648
28.56230197 -80.57735648
28.56230197 -80.57735648
28.56230197 -80.57735648
28.56230197 -80.57735648
28.56230197 -80.57735648
28.56230197 -80.57735648
28.56230197 -80.57735648
28.56230197 -80.57735648
28.56230197 -80.57735648
28.56230197 -80.57735648
28.56230197 -80.57735648
28.56230197 -80.57735648
34.63283416 -120.6107455
34.63283416 -120.6107455
34.63283416 -120.6107455
34.63283416 -120.6107455
34.63283416 -120.6107455
34.63283416 -120.6107455
34.63283416 -120.6107455
34.63283416 -120.6107455
34.63283416 -120.6107455
34.63283416 -120.6107455
28.57325457 -80.64689529
28.57325457 -80.64689529
28.57325457 -80.64689529
28.57325457 -80.64689529
28.57325457 -80.64689529
28.57325457 -80.64689529
28.57325457 -80.64689529
28.57325457 -80.64689529
28.57325457 -80.64689529
28.57325457 -80.64689529
28.57325457 -80.64689529
28.57325457 -80.64689529
28.57325457 -80.64689529
28.56319718 -80.57682003
28.56319718 -80.57682003
28.56319718 -80.57682003
28.56319718 -80.57682003
28.56319718 -80.57682003
28.56319718 -80.57682003
28.56319718 -80.57682003

In [17]:
spacex_df = spacex_df[['Launch Site', 'Lat', 'Long', 'class']]

In [18]:
launch_sites_df = spacex_df.groupby(["Launch Site"], as_index=False).first()

In [19]:
launch_sites_df

    Launch Site        Lat        Long  class
0   CCAFS LC-40  28.562302  -80.577356      0
1  CCAFS SLC-40  28.563197  -80.576820      1
2    KSC LC-39A  28.573255  -80.646895      1
3   VAFB SLC-4E  34.632834 -120.610745      0

In [20]:
nasa_coordinate = [29.559684888503615, -95.0830971930759]
site_map = folium.Map(location=nasa_coordinate, zoom_start=10)

In [21]:
site_map

In [22]:
circle = folium.Circle(nasa_coordinate,radius=1000,color='#d35400',fill = True).add_child(folium.Popup("NASA Johnson Space Center"))

marker = folium.map.Marker(
    nasa_coordinate,

    icon = DivIcon(
        icon_size=(20,20),
        icon_anchor =(0,0),
        html='<div style="font-size: 12; color:#d35400;"><b>%s</b></div>' % 'NASA JSC',
    )
)
site_map.add_child(circle)
site_map.add_child(marker)


### add circles

In [23]:
launch_sites_df

    Launch Site        Lat        Long  class
0   CCAFS LC-40  28.562302  -80.577356      0
1  CCAFS SLC-40  28.563197  -80.576820      1
2    KSC LC-39A  28.573255  -80.646895      1
3   VAFB SLC-4E  34.632834 -120.610745      0

In [24]:
spacex_map = folium.Map(location=[39.8283,-98.5795],zoom_start=4,tiles="Cartodb positron")

In [26]:
for latitude, longitude, site in zip(launch_sites_df.Lat,launch_sites_df.Long,launch_sites_df["Launch Site"]):
    circle = folium.Circle(location=[latitude, longitude],radius=1000,color="blue",fill=True).add_child(folium.Popup(site))

    marker = folium.map.Marker(
        location=[latitude, longitude],

        icon=DivIcon(
            icon_size=(20,20),
            icon_anchor=(0,0),
            html='<div style="font-size: 12; color:#d35400;"><b>%s</b></div>' % site,
        )
    )
    spacex_map.add_child(circle)
    spacex_map.add_child(marker)
spacex_map

## task2

In [27]:
spacex_df

     Launch Site        Lat        Long  class
0    CCAFS LC-40  28.562302  -80.577356      0
1    CCAFS LC-40  28.562302  -80.577356      0
2    CCAFS LC-40  28.562302  -80.577356      0
3    CCAFS LC-40  28.562302  -80.577356      0
4    CCAFS LC-40  28.562302  -80.577356      0
5    CCAFS LC-40  28.562302  -80.577356      0
6    CCAFS LC-40  28.562302  -80.577356      0
7    CCAFS LC-40  28.562302  -80.577356      0
8    CCAFS LC-40  28.562302  -80.577356      0
9    CCAFS LC-40  28.562302  -80.577356      0
10   CCAFS LC-40  28.562302  -80.577356      0
11   CCAFS LC-40  28.562302  -80.577356      0
12   CCAFS LC-40  28.562302  -80.577356      0
13   CCAFS LC-40  28.562302  -80.577356      0
14   CCAFS LC-40  28.562302  -80.577356      0
15   CCAFS LC-40  28.562302  -80.577356      0
16   CCAFS LC-40  28.562302  -80.577356      0
17   CCAFS LC-40  28.562302  -80.577356      1
18   CCAFS LC-40  28.562302  -80.577356      1
19   CCAFS LC-40  28.562302  -80.577356      0
20   CCAFS LC-40  28.562302  -80.577356      1
21   CCAFS LC-40  28.562302  -80.577356      1
22   CCAFS LC-40  28.562302  -80.577356      1
23   CCAFS LC-40  28.562302  -80.577356      0
24   CCAFS LC-40  28.562302  -80.577356      1
25   CCAFS LC-40  28.562302  -80.577356      1
26   VAFB SLC-4E  34.632834 -120.610745      0
27   VAFB SLC-4E  34.632834 -120.610745      0
28   VAFB SLC-4E  34.632834 -120.610745      1
29   VAFB SLC-4E  34.632834 -120.610745      1
30   VAFB SLC-4E  34.632834 -120.610745      1
31   VAFB SLC-4E  34.632834 -120.610745      1
32   VAFB SLC-4E  34.632834 -120.610745      0
33   VAFB SLC-4E  34.632834 -120.610745      0
34   VAFB SLC-4E  34.632834 -120.610745      0
35   VAFB SLC-4E  34.632834 -120.610745      0
36    KSC LC-39A  28.573255  -80.646895      1
37    KSC LC-39A  28.573255  -80.646895      0
38    KSC LC-39A  28.573255  -80.646895      1
39    KSC LC-39A  28.573255  -80.646895      1
40    KSC LC-39A  28.573255  -80.646895      0
41    KSC LC-39A  28.573255  -80.646895      1
42    KSC LC-39A  28.573255  -80.646895      1
43    KSC LC-39A  28.573255  -80.646895      0
44    KSC LC-39A  28.573255  -80.646895      1
45    KSC LC-39A  28.573255  -80.646895      1
46    KSC LC-39A  28.573255  -80.646895      1
47    KSC LC-39A  28.573255  -80.646895      1
48    KSC LC-39A  28.573255  -80.646895      1
49  CCAFS SLC-40  28.563197  -80.576820      1
50  CCAFS SLC-40  28.563197  -80.576820      1
51  CCAFS SLC-40  28.563197  -80.576820      0
52  CCAFS SLC-40  28.563197  -80.576820      0
53  CCAFS SLC-40  28.563197  -80.576820      0
54  CCAFS SLC-40  28.563197  -80.576820      1
55  CCAFS SLC-40  28.563197  -80.576820      0

In [58]:
launch_count = spacex_df.groupby("Launch Site")["class"].count().to_frame()

In [59]:
launch_count

              class
Launch Site
CCAFS LC-40      26
CCAFS SLC-40      7
KSC LC-39A       13
VAFB SLC-4E      10

In [60]:
successful_launches = spacex_df.groupby("Launch Site")["class"].sum().to_frame()

In [61]:
successful_launches

              class
Launch Site
CCAFS LC-40       7
CCAFS SLC-40      3
KSC LC-39A       10
VAFB SLC-4E       4

In [62]:
unsuccessful_launches = launch_count - successful_launches

In [63]:
unsuccessful_launches

              class
Launch Site
CCAFS LC-40      19
CCAFS SLC-40      4
KSC LC-39A        3
VAFB SLC-4E       6

In [48]:
success_df = pd.concat([launch_count,successful_launches,unsuccessful_launches],axis=1)

In [64]:
success_df.columns = ["launch_count","successful_launches","unsuccessful_launches"]

In [65]:
success_df

              launch_count  successful_launches  unsuccessful_launches
Launch Site
CCAFS LC-40             26                    7                     19
CCAFS SLC-40             7                    3                      4
KSC LC-39A              13                   10                      3
VAFB SLC-4E             10                    4                      6

In [68]:
new_df = pd.concat([success_df,launch_sites_df.set_index("Launch Site")[["Lat","Long"]]],axis=1)

In [69]:
new_df

,launch_count,successful_launches,unsuccessful_launches,Lat,Long
Launch Site,,,,,
CCAFS LC-40,26,7,19,28.562302,-80.577356
CCAFS SLC-40,7,3,4,28.563197,-80.576820
KSC LC-39A,13,10,3,28.573255,-80.646895
VAFB SLC-4E,10,4,6,34.632834,-120.610745

In [73]:
for launch_count, successful_launches, unsuccessful_launches, lat, long in zip(
    new_df.launch_count,new_df.successful_launches,new_df.unsuccessful_launches, new_df.Lat, new_df.Long):
    
    marker = folium.map.Marker(
        location = [lat,long],
        icon_size=(20,20),
        icon_anchor = (0,0),
        html=f'<div style="font-size: 12; color:#d35400;"><b> Launch Count:{launch_count}, Successful Launches: {successful_launches}, Unsuccessful Launches: {unsuccessful_launches}</b></div>',
    )
    spacex_map.add_child(marker)

In [74]:
spacex_map

In [75]:
mapax = folium.Map(location=[39.8283,-98.5795],zoom_start=4,tiles="Cartodb positron")

In [76]:
for launch_count, successful_launches, unsuccessful_launches, lat, long in zip(
    new_df.launch_count,new_df.successful_launches,new_df.unsuccessful_launches, new_df.Lat, new_df.Long):
    
    marker = folium.map.Marker(
        location = [lat,long],
        icon_size=(20,20),
        icon_anchor = (0,0),
        html=f'<div style="font-size: 12; color:#d35400;"><b> Launch Count:{launch_count}, Successful Launches: {successful_launches}, Unsuccessful Launches: {unsuccessful_launches}</b></div>',
    )
    mapax.add_child(marker)
mapax

In [78]:
new_df.reset_index(inplace=True)

In [79]:
new_df

,Launch Site,launch_count,successful_launches,unsuccessful_launches,Lat,Long
0,CCAFS LC-40,26,7,19,28.562302,-80.577356
1,CCAFS SLC-40,7,3,4,28.563197,-80.576820
2,KSC LC-39A,13,10,3,28.573255,-80.646895
3,VAFB SLC-4E,10,4,6,34.632834,-120.610745

In [81]:
mapay = folium.Map(location=[39.8283,-98.5795],zoom_start=4,tiles="Cartodb positron")

for l_site, launch_count, successful_launches, unsuccessful_launches, lat, long in zip(
    new_df["Launch Site"],new_df.launch_count,new_df.successful_launches,new_df.unsuccessful_launches, new_df.Lat, new_df.Long):

    circle = folium.Circle(location=[lat,long], radius=1000, color='#d35400', fill=True).add_child(folium.Popup(f'Launch Site: {l_site},Launch Count:{launch_count}, Successful Launches: {successful_launches}, Unsuccessful Launches: {unsuccessful_launches}'))

    marker = folium.map.Marker(
        location=[lat, long],

        icon=DivIcon(
            icon_size=(20,20),
            icon_anchor=(0,0),
            html='<div style="font-size: 12; color:#d35400;"><b>%s</b></div>' % l_site,
        )
    )
    
    mapay.add_child(circle)
    mapay.add_child(marker)
mapay

In [82]:
new_df

,Launch Site,launch_count,successful_launches,unsuccessful_launches,Lat,Long
0,CCAFS LC-40,26,7,19,28.562302,-80.577356
1,CCAFS SLC-40,7,3,4,28.563197,-80.576820
2,KSC LC-39A,13,10,3,28.573255,-80.646895
3,VAFB SLC-4E,10,4,6,34.632834,-120.610745

In [83]:
new_df["sucess_rate"] = new_df["successful_launches"]/new_df["launch_count"]

In [84]:
new_df

,Launch Site,launch_count,successful_launches,unsuccessful_launches,Lat,Long,sucess_rate
0,CCAFS LC-40,26,7,19,28.562302,-80.577356,0.269231
1,CCAFS SLC-40,7,3,4,28.563197,-80.576820,0.428571
2,KSC LC-39A,13,10,3,28.573255,-80.646895,0.769231
3,VAFB SLC-4E,10,4,6,34.632834,-120.610745,0.400000

In [85]:
marker_cluster = MarkerCluster()

In [ ]:
space_x["marker_color"] =

In [87]:
spacex_df["marker_color"] = spacex_df["class"]

In [88]:
spacex_df

     Launch Site        Lat        Long  class  marker_color
0    CCAFS LC-40  28.562302  -80.577356      0             0
1    CCAFS LC-40  28.562302  -80.577356      0             0
2    CCAFS LC-40  28.562302  -80.577356      0             0
3    CCAFS LC-40  28.562302  -80.577356      0             0
4    CCAFS LC-40  28.562302  -80.577356      0             0
5    CCAFS LC-40  28.562302  -80.577356      0             0
6    CCAFS LC-40  28.562302  -80.577356      0             0
7    CCAFS LC-40  28.562302  -80.577356      0             0
8    CCAFS LC-40  28.562302  -80.577356      0             0
9    CCAFS LC-40  28.562302  -80.577356      0             0
10   CCAFS LC-40  28.562302  -80.577356      0             0
11   CCAFS LC-40  28.562302  -80.577356      0             0
12   CCAFS LC-40  28.562302  -80.577356      0             0
13   CCAFS LC-40  28.562302  -80.577356      0             0
14   CCAFS LC-40  28.562302  -80.577356      0             0
15   CCAFS LC-40  28.562302  -80.577356      0             0
16   CCAFS LC-40  28.562302  -80.577356      0             0
17   CCAFS LC-40  28.562302  -80.577356      1             1
18   CCAFS LC-40  28.562302  -80.577356      1             1
19   CCAFS LC-40  28.562302  -80.577356      0             0
20   CCAFS LC-40  28.562302  -80.577356      1             1
21   CCAFS LC-40  28.562302  -80.577356      1             1
22   CCAFS LC-40  28.562302  -80.577356      1             1
23   CCAFS LC-40  28.562302  -80.577356      0             0
24   CCAFS LC-40  28.562302  -80.577356      1             1
25   CCAFS LC-40  28.562302  -80.577356      1             1
26   VAFB SLC-4E  34.632834 -120.610745      0             0
27   VAFB SLC-4E  34.632834 -120.610745      0             0
28   VAFB SLC-4E  34.632834 -120.610745      1             1
29   VAFB SLC-4E  34.632834 -120.610745      1             1
30   VAFB SLC-4E  34.632834 -120.610745      1             1
31   VAFB SLC-4E  34.632834 -120.610745      1             1
32   VAFB SLC-4E  34.632834 -120.610745      0             0
33   VAFB SLC-4E  34.632834 -120.610745      0             0
34   VAFB SLC-4E  34.632834 -120.610745      0             0
35   VAFB SLC-4E  34.632834 -120.610745      0             0
36    KSC LC-39A  28.573255  -80.646895      1             1
37    KSC LC-39A  28.573255  -80.646895      0             0
38    KSC LC-39A  28.573255  -80.646895      1             1
39    KSC LC-39A  28.573255  -80.646895      1             1
40    KSC LC-39A  28.573255  -80.646895      0             0
41    KSC LC-39A  28.573255  -80.646895      1             1
42    KSC LC-39A  28.573255  -80.646895      1             1
43    KSC LC-39A  28.573255  -80.646895      0             0
44    KSC LC-39A  28.573255  -80.646895      1             1
45    KSC LC-39A  28.573255  -80.646895      1             1
46    KSC LC-39A  28.573255  -80.646895      1             1
47    KSC LC-39A  28.573255  -80.646895      1             1
48    KSC LC-39A  28.573255  -80.646895      1             1
49  CCAFS SLC-40  28.563197  -80.576820      1             1
50  CCAFS SLC-40  28.563197  -80.576820      1             1
51  CCAFS SLC-40  28.563197  -80.576820      0             0
52  CCAFS SLC-40  28.563197  -80.576820      0             0
53  CCAFS SLC-40  28.563197  -80.576820      0             0
54  CCAFS SLC-40  28.563197  -80.576820      1             1
55  CCAFS SLC-40  28.563197  -80.576820      0             0

In [89]:
spacex_df.dtypes

Launch Site         str
Lat             float64
Long            float64
class             int64
marker_color      int64
dtype: object

In [95]:
def correct_color(dataframe):
    dataframe["marker_color"] = dataframe["marker_color"].astype(str)
    dataframe["marker_color"] = dataframe["marker_color"].map({"1":"green","0":"red"})

In [96]:
correct_color(spacex_df)

In [97]:
spacex_df

     Launch Site        Lat        Long  class marker_color
0    CCAFS LC-40  28.562302  -80.577356      0          red
1    CCAFS LC-40  28.562302  -80.577356      0          red
2    CCAFS LC-40  28.562302  -80.577356      0          red
3    CCAFS LC-40  28.562302  -80.577356      0          red
4    CCAFS LC-40  28.562302  -80.577356      0          red
5    CCAFS LC-40  28.562302  -80.577356      0          red
6    CCAFS LC-40  28.562302  -80.577356      0          red
7    CCAFS LC-40  28.562302  -80.577356      0          red
8    CCAFS LC-40  28.562302  -80.577356      0          red
9    CCAFS LC-40  28.562302  -80.577356      0          red
10   CCAFS LC-40  28.562302  -80.577356      0          red
11   CCAFS LC-40  28.562302  -80.577356      0          red
12   CCAFS LC-40  28.562302  -80.577356      0          red
13   CCAFS LC-40  28.562302  -80.577356      0          red
14   CCAFS LC-40  28.562302  -80.577356      0          red
15   CCAFS LC-40  28.562302  -80.577356      0          red
16   CCAFS LC-40  28.562302  -80.577356      0          red
17   CCAFS LC-40  28.562302  -80.577356      1        green
18   CCAFS LC-40  28.562302  -80.577356      1        green
19   CCAFS LC-40  28.562302  -80.577356      0          red
20   CCAFS LC-40  28.562302  -80.577356      1        green
21   CCAFS LC-40  28.562302  -80.577356      1        green
22   CCAFS LC-40  28.562302  -80.577356      1        green
23   CCAFS LC-40  28.562302  -80.577356      0          red
24   CCAFS LC-40  28.562302  -80.577356      1        green
25   CCAFS LC-40  28.562302  -80.577356      1        green
26   VAFB SLC-4E  34.632834 -120.610745      0          red
27   VAFB SLC-4E  34.632834 -120.610745      0          red
28   VAFB SLC-4E  34.632834 -120.610745      1        green
29   VAFB SLC-4E  34.632834 -120.610745      1        green
30   VAFB SLC-4E  34.632834 -120.610745      1        green
31   VAFB SLC-4E  34.632834 -120.610745      1        green
32   VAFB SLC-4E  34.632834 -120.610745      0          red
33   VAFB SLC-4E  34.632834 -120.610745      0          red
34   VAFB SLC-4E  34.632834 -120.610745      0          red
35   VAFB SLC-4E  34.632834 -120.610745      0          red
36    KSC LC-39A  28.573255  -80.646895      1        green
37    KSC LC-39A  28.573255  -80.646895      0          red
38    KSC LC-39A  28.573255  -80.646895      1        green
39    KSC LC-39A  28.573255  -80.646895      1        green
40    KSC LC-39A  28.573255  -80.646895      0          red
41    KSC LC-39A  28.573255  -80.646895      1        green
42    KSC LC-39A  28.573255  -80.646895      1        green
43    KSC LC-39A  28.573255  -80.646895      0          red
44    KSC LC-39A  28.573255  -80.646895      1        green
45    KSC LC-39A  28.573255  -80.646895      1        green
46    KSC LC-39A  28.573255  -80.646895      1        green
47    KSC LC-39A  28.573255  -80.646895      1        green
48    KSC LC-39A  28.573255  -80.646895      1        green
49  CCAFS SLC-40  28.563197  -80.576820      1        green
50  CCAFS SLC-40  28.563197  -80.576820      1        green
51  CCAFS SLC-40  28.563197  -80.576820      0          red
52  CCAFS SLC-40  28.563197  -80.576820      0          red
53  CCAFS SLC-40  28.563197  -80.576820      0          red
54  CCAFS SLC-40  28.563197  -80.576820      1        green
55  CCAFS SLC-40  28.563197  -80.576820      0          red

In [98]:
spacex_map

In [99]:
mapay

In [101]:
mapay.add_child(marker_cluster)

In [102]:
spacex_df

     Launch Site        Lat        Long  class marker_color
0    CCAFS LC-40  28.562302  -80.577356      0          red
1    CCAFS LC-40  28.562302  -80.577356      0          red
2    CCAFS LC-40  28.562302  -80.577356      0          red
3    CCAFS LC-40  28.562302  -80.577356      0          red
4    CCAFS LC-40  28.562302  -80.577356      0          red
5    CCAFS LC-40  28.562302  -80.577356      0          red
6    CCAFS LC-40  28.562302  -80.577356      0          red
7    CCAFS LC-40  28.562302  -80.577356      0          red
8    CCAFS LC-40  28.562302  -80.577356      0          red
9    CCAFS LC-40  28.562302  -80.577356      0          red
10   CCAFS LC-40  28.562302  -80.577356      0          red
11   CCAFS LC-40  28.562302  -80.577356      0          red
12   CCAFS LC-40  28.562302  -80.577356      0          red
13   CCAFS LC-40  28.562302  -80.577356      0          red
14   CCAFS LC-40  28.562302  -80.577356      0          red
15   CCAFS LC-40  28.562302  -80.577356      0          red
16   CCAFS LC-40  28.562302  -80.577356      0          red
17   CCAFS LC-40  28.562302  -80.577356      1        green
18   CCAFS LC-40  28.562302  -80.577356      1        green
19   CCAFS LC-40  28.562302  -80.577356      0          red
20   CCAFS LC-40  28.562302  -80.577356      1        green
21   CCAFS LC-40  28.562302  -80.577356      1        green
22   CCAFS LC-40  28.562302  -80.577356      1        green
23   CCAFS LC-40  28.562302  -80.577356      0          red
24   CCAFS LC-40  28.562302  -80.577356      1        green
25   CCAFS LC-40  28.562302  -80.577356      1        green
26   VAFB SLC-4E  34.632834 -120.610745      0          red
27   VAFB SLC-4E  34.632834 -120.610745      0          red
28   VAFB SLC-4E  34.632834 -120.610745      1        green
29   VAFB SLC-4E  34.632834 -120.610745      1        green
30   VAFB SLC-4E  34.632834 -120.610745      1        green
31   VAFB SLC-4E  34.632834 -120.610745      1        green
32   VAFB SLC-4E  34.632834 -120.610745      0          red
33   VAFB SLC-4E  34.632834 -120.610745      0          red
34   VAFB SLC-4E  34.632834 -120.610745      0          red
35   VAFB SLC-4E  34.632834 -120.610745      0          red
36    KSC LC-39A  28.573255  -80.646895      1        green
37    KSC LC-39A  28.573255  -80.646895      0          red
38    KSC LC-39A  28.573255  -80.646895      1        green
39    KSC LC-39A  28.573255  -80.646895      1        green
40    KSC LC-39A  28.573255  -80.646895      0          red
41    KSC LC-39A  28.573255  -80.646895      1        green
42    KSC LC-39A  28.573255  -80.646895      1        green
43    KSC LC-39A  28.573255  -80.646895      0          red
44    KSC LC-39A  28.573255  -80.646895      1        green
45    KSC LC-39A  28.573255  -80.646895      1        green
46    KSC LC-39A  28.573255  -80.646895      1        green
47    KSC LC-39A  28.573255  -80.646895      1        green
48    KSC LC-39A  28.573255  -80.646895      1        green
49  CCAFS SLC-40  28.563197  -80.576820      1        green
50  CCAFS SLC-40  28.563197  -80.576820      1        green
51  CCAFS SLC-40  28.563197  -80.576820      0          red
52  CCAFS SLC-40  28.563197  -80.576820      0          red
53  CCAFS SLC-40  28.563197  -80.576820      0          red
54  CCAFS SLC-40  28.563197  -80.576820      1        green
55  CCAFS SLC-40  28.563197  -80.576820      0          red

In [107]:
mapaz = folium.Map(location=[39.8283,-98.5795],zoom_start=4,tiles="Cartodb positron")
mapaz.add_child(marker_cluster)
for lat,long,color in zip(spacex_df.Lat,spacex_df.Long,spacex_df.marker_color):

    marker = folium.Marker(
        location = [lat,long],
        icon = folium.Icon(color=color)
    )
    marker_cluster.add_child(marker)
mapaz

In [108]:
mapaw = folium.Map(location=[39.8283,-98.5795],zoom_start=4,tiles="Cartodb positron")

for l_site, launch_count, successful_launches, unsuccessful_launches, lat, long in zip(
    new_df["Launch Site"],new_df.launch_count,new_df.successful_launches,new_df.unsuccessful_launches, new_df.Lat, new_df.Long):

    circle = folium.Circle(location=[lat,long], radius=1000, color='#d35400', fill=True).add_child(folium.Popup(f'Launch Site: {l_site},Launch Count:{launch_count}, Successful Launches: {successful_launches}, Unsuccessful Launches: {unsuccessful_launches}'))

    marker = folium.map.Marker(
        location=[lat, long],

        icon=DivIcon(
            icon_size=(20,20),
            icon_anchor=(0,0),
            html='<div style="font-size: 12; color:#d35400;"><b>%s</b></div>' % l_site,
        )
    )
    
    mapaw.add_child(circle)
    mapaw.add_child(marker)

mapaw.add_child(marker_cluster)
for lat,long,color in zip(spacex_df.Lat,spacex_df.Long,spacex_df.marker_color):

    marker = folium.Marker(
        location = [lat,long],
        icon = folium.Icon(color=color)
    )
    marker_cluster.add_child(marker)


mapaw

## task3

In [109]:
# Add Mouse Position to get the coordinate (Lat, Long) for a mouse over on the map
formatter = "function(num) {return L.Util.formatNum(num, 5);};"
mouse_position = MousePosition(
    position='topright',
    separator=' Long: ',
    empty_string='NaN',
    lng_first=False,
    num_digits=20,
    prefix='Lat:',
    lat_formatter=formatter,
    lng_formatter=formatter,
)

mapaw.add_child(mouse_position)
mapaw

In [110]:
from math import sin, cos, sqrt, atan2, radians

def calculate_distance(lat1, lon1, lat2, lon2):
    # approximate radius of earth in km
    R = 6373.0

    lat1 = radians(lat1)
    lon1 = radians(lon1)
    lat2 = radians(lat2)
    lon2 = radians(lon2)

    dlon = lon2 - lon1
    dlat = lat2 - lat1

    a = sin(dlat / 2)**2 + cos(lat1) * cos(lat2) * sin(dlon / 2)**2
    c = 2 * atan2(sqrt(a), sqrt(1 - a))

    distance = R * c
    return distance

In [111]:
railway_coord = [28.57196,-80.65392]

In [115]:
spacex_df[spacex_df["Launch Site"]=="KSC LC-39A"]

   Launch Site        Lat       Long  class marker_color
36  KSC LC-39A  28.573255 -80.646895      1        green
37  KSC LC-39A  28.573255 -80.646895      0          red
38  KSC LC-39A  28.573255 -80.646895      1        green
39  KSC LC-39A  28.573255 -80.646895      1        green
40  KSC LC-39A  28.573255 -80.646895      0          red
41  KSC LC-39A  28.573255 -80.646895      1        green
42  KSC LC-39A  28.573255 -80.646895      1        green
43  KSC LC-39A  28.573255 -80.646895      0          red
44  KSC LC-39A  28.573255 -80.646895      1        green
45  KSC LC-39A  28.573255 -80.646895      1        green
46  KSC LC-39A  28.573255 -80.646895      1        green
47  KSC LC-39A  28.573255 -80.646895      1        green
48  KSC LC-39A  28.573255 -80.646895      1        green

In [119]:
distance = calculate_distance(28.562302, -80.577356, 28.56387, -80.56808)

In [120]:
marker = folium.Marker(
    location = [28.56387, -80.56808],
    icon= DivIcon(
        icon_size = (20,20),
        icon_anchor = (0,0),
        html='<div style="font-size: 12; color:#d35400;"><b>%s</b></div>' % "{:10.2f} KM".format(distance),
    )
)

mapaw.add_child(marker)
mapaw

In [122]:
lines = folium.PolyLine(locations = [[28.562302, -80.577356],[28.56387, -80.56808]],weight = 1)
mapaw.add_child(lines)
mapaw

In [123]:
railway_line = folium.PolyLine(locations = [[28.562302, -80.577356],[28.56408,-80.5868]],weight = 1)
mapaw.add_child(railway_line)
mapaw

In [124]:
railway_marker = folium.Marker(
    location = [28.56408,-80.5868],
    icon = DivIcon(
        icon_size = (20,20),
        icon_anchor = (0,0),
        html='<div style="font-size: 12; color:#d35400;"><b>Closest Railway</b></div>',
    )
)
mapaw.add_child(railway_marker)
mapaw

In [125]:
type(mapaw)

folium.folium.Map

In [126]:
type(marker_cluster)

folium.plugins.marker_cluster.MarkerCluster